spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DEV_DB_HOST:localhost}:${DEV_DB_PORT:5432}/${DB_NAME:clevertec-banking}?currentSchema=${DEFAULT_SCHEMA:currency}
    username: ${DEV_DB_USERNAME:postgres}
    password: ${DEV_DB_USERNAME:postgres}
  liquibase:
    default-schema: ${DEFAULT_SCHEMA:currency}
    change-log: db/changelog/db.changelog.yaml
    liquibase-schema: ${DEFAULT_SCHEMA:currency}
  rabbitmq:
    port: ${DEV_RABBIT_PORT:5672}
    host: ${DEV_RABBIT_HOST:localhost}
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA:currency}
        format_sql: true

clevertec:
  rabbit:
    queue:
      currency: ${RABBIT_CURRENCY_QUEUE:currency}

logging:
  level:
    org:
      hibernate:
        type: trace
eureka:
  client:
    service-url:
      defaultZone : http://${DEV_EUREKA_HOST:localhost}:${DEV_EUREKA_PORT:8761}/eureka/
