spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DEFAULT_SCHEMA}
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: ${DEFAULT_SCHEMA}
    liquibase-schema: ${DEFAULT_SCHEMA}
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
    port: ${PROD_RABBIT_PORT}
    host: ${PROD_RABBIT_HOST}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  data:
    redis:
      password: ${PROD_REDIS_PASSWORD}
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
      database: ${PROD_REDIS_DATABASE}

eureka:
  client:
    service-url:
      defaultZone: http://${PROD_EUREKA_HOST}:${PROD_EUREKA_PORT}/eureka/

clevertec:
  rabbit:
    config:
      name-forward-exchange: ${RABBIT_AUTH_EXCHANGE}
      queue-name: ${RABBIT_CUSTOMER_QUEUE}
  feign:
    client:
      account-card:
        name: ACCOUNT-CARD-SERVICE
        path: ${ACCOUNT_CARD_PATH}
      credit:
        name: CREDIT-SERVICE
        path: ${CREDIT_PATH}
      deposit:
        name: DEPOSIT-SERVICE
        path: ${DEPOSIT_PATH}
